# Generated by Django 4.2.2 on 2023-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='db',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='使用者名稱'),
        ),
    ]
