# Generated by Django 4.2.2 on 2023-06-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
            options={
                'db_table': 'nre_customer',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customer', verbose_name='customer')),
            ],
            options={
                'db_table': 'nre_function',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('power_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='power ratio')),
            ],
            options={
                'db_table': 'nre_project',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.function', verbose_name='function')),
            ],
            options={
                'db_table': 'nre_test_item',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_test_uut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='concept_test_uut')),
                ('concept_need_test', models.BooleanField(default=False, verbose_name='concept_need_test')),
                ('concept_regression_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='concept_regression_rate')),
                ('bu_test_uut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='bu_test_uut')),
                ('bu_need_test', models.BooleanField(default=False, verbose_name='bu_need_test')),
                ('bu_regression_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='bu_regression_rate')),
                ('ct_test_uut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ct_test_uut')),
                ('ct_need_test', models.BooleanField(default=False, verbose_name='ct_need_test')),
                ('ct_regression_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ct_regression_rate')),
                ('nt_test_uut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nt_test_uut')),
                ('nt_need_test', models.BooleanField(default=False, verbose_name='nt_need_test')),
                ('nt_regression_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nt_regression_rate')),
                ('ot_test_uut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ot_test_uut')),
                ('ot_need_test', models.BooleanField(default=False, verbose_name='ot_need_test')),
                ('ot_regression_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ot_regression_rate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project', verbose_name='project')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.testitem', verbose_name='test_item')),
            ],
            options={
                'db_table': 'nre_record',
                'unique_together': {('project', 'test_item')},
            },
        ),
    ]
