# Generated by Django 4.2.2 on 2023-06-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='project',
        ),
        migrations.AddField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.project', verbose_name='project'),
        ),
    ]
