# Generated by Django 4.2.2 on 2023-07-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.item', verbose_name='item'),
            preserve_default=False,
        ),
    ]
