# Generated by Django 4.2.2 on 2023-06-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_customer_project_record_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project', verbose_name='project'),
        ),
    ]
