# Generated by Django 4.2.2 on 2023-06-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_record_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
    ]
