# Generated by Django 4.2.2 on 2023-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_testitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(default=1, max_length=120, verbose_name='desc'),
            preserve_default=False,
        ),
    ]
