# Generated by Django 4.2.2 on 2023-06-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_record_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('project', 'test_item')},
        ),
    ]
