# Generated by Django 4.2.2 on 2023-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_item_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desc',
        ),
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.CharField(default=1, max_length=120, verbose_name='no'),
            preserve_default=False,
        ),
    ]
