# Generated by Django 4.2.2 on 2023-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_item_desc_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='equip_working_hour',
        ),
        migrations.AddField(
            model_name='item',
            name='equip_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='equip_working_hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='man_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='man_working_hours'),
            preserve_default=False,
        ),
    ]
