# Generated by Django 4.2.2 on 2023-06-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_record_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='db.project', verbose_name='project'),
        ),
    ]
