# Generated by Django 4.2.2 on 2023-07-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_item_equip_working_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.customer', verbose_name='customer'),
            preserve_default=False,
        ),
    ]
