# Generated by Django 4.2.2 on 2023-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_project_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='equip_working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='equip_working_hours'),
        ),
        migrations.AlterField(
            model_name='item',
            name='man_working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='man_working_hours'),
        ),
    ]
