# Generated by Django 4.2.2 on 2023-06-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_record_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='record',
            name='bu_test_uut',
            field=models.IntegerField(blank=True, null=True, verbose_name='bu_test_uut'),
        ),
        migrations.AlterField(
            model_name='record',
            name='concept_test_uut',
            field=models.IntegerField(blank=True, null=True, verbose_name='concept_test_uut'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ct_test_uut',
            field=models.IntegerField(blank=True, null=True, verbose_name='ct_test_uut'),
        ),
        migrations.AlterField(
            model_name='record',
            name='nt_test_uut',
            field=models.IntegerField(blank=True, null=True, verbose_name='nt_test_uut'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ot_test_uut',
            field=models.IntegerField(blank=True, null=True, verbose_name='ot_test_uut'),
        ),
    ]
