# Generated by Django 4.2.2 on 2023-07-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_item_equip_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.item', verbose_name='item'),
        ),
    ]
