# Generated by Django 4.2.2 on 2023-07-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_testitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='no',
        ),
        migrations.AlterField(
            model_name='fee',
            name='test_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='db.testitem', verbose_name='test_item'),
        ),
    ]
