# Generated by Django 4.2.2 on 2023-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_item_no_alter_fee_test_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
    ]
