# Generated by Django 4.2.2 on 2023-07-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='test_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='db.testitem', verbose_name='fee'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='lab_location',
            field=models.CharField(max_length=120, verbose_name='lab_location'),
        ),
    ]
