# Generated by Django 4.2.2 on 2023-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_fee_test_item_alter_testitem_lab_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='no'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
