# Generated by Django 4.2.2 on 2023-07-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_item_no_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.CharField(max_length=120, unique=True, verbose_name='no'),
        ),
    ]
