# Generated by Django 4.2.2 on 2023-07-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_alter_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default=1, max_length=120, verbose_name='version'),
            preserve_default=False,
        ),
    ]
