# Generated by Django 4.2.2 on 2023-07-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_project_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'version')},
        ),
    ]
