# Generated by Django 4.2.2 on 2023-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
