# Generated by Django 4.2.2 on 2023-07-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_testitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='walk_in',
            field=models.BooleanField(default=False, verbose_name='concept_need_test'),
        ),
    ]
