# Generated by Django 4.2.2 on 2023-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_record_walk_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='walk_in',
            field=models.BooleanField(default=False, verbose_name='walk_in'),
        ),
    ]
