# Generated by Django 4.2.2 on 2023-07-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_alter_record_walk_in'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('customer', 'name', 'version')},
        ),
    ]
