# Generated by Django 4.2.2 on 2023-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_chamber_alter_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
