# Generated by Django 4.2.2 on 2023-08-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_alter_customer_created_at_alter_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='man_hours')),
                ('equip_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='equip_hours')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarys', to='db.project', verbose_name='project')),
            ],
        ),
    ]
