# Generated by Django 4.2.2 on 2023-08-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='equip_hours',
            new_name='equip_hrs',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='man_hours',
            new_name='man_hrs',
        ),
    ]
