# Generated by Django 4.2.2 on 2023-08-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_rename_equip_hours_summary_equip_hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='crated at'),
        ),
        migrations.AddField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated at'),
        ),
    ]
