# Generated by Django 4.2.2 on 2023-08-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_summary_created_at_summary_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='crated at'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
