# Generated by Django 4.2.2 on 2023-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_alter_summary_created_at_alter_summary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='equip_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='equip_hours'),
        ),
        migrations.AddField(
            model_name='project',
            name='man_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='man_hours'),
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
