# Generated by Django 4.2.2 on 2023-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_project_equip_hrs_project_man_hrs_delete_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='fees'),
        ),
    ]
