# Generated by Django 4.2.2 on 2023-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_project_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pkg_bu_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_bu_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_bu_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_bu_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_bu_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_bu_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_concept_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_concept_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_concept_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_concept_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_concept_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_concept_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_ct_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_ct_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_ct_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_ct_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_ct_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_ct_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_nt_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_nt_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_nt_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_nt_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_nt_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_nt_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_ot_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_ot_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_ot_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_ot_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='pkg_ot_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pkg_ot_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_bu_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_bu_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_bu_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_bu_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_bu_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_bu_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_concept_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_concept_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_concept_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_concept_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_concept_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_concept_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_ct_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_ct_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_ct_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_ct_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_ct_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_ct_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_nt_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_nt_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_nt_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_nt_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_nt_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_nt_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_ot_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_ot_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_ot_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_ot_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='rel_ot_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rel_ot_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_bu_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_bu_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_bu_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_bu_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_bu_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_bu_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_concept_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_concept_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_concept_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_concept_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_concept_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_concept_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_ct_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_ct_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_ct_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_ct_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_ct_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_ct_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_nt_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_nt_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_nt_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_nt_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_nt_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_nt_hr'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_ot_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_ot_duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_ot_duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_ot_duty_rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='sv_ot_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sv_ot_hr'),
        ),
    ]
