# Generated by Django 4.2.2 on 2023-08-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_project_pkg_bu_duration_project_pkg_bu_duty_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rel_concept_duration',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='rel_concept_duration'),
        ),
    ]
