# Generated by Django 4.2.2 on 2023-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_alter_project_rel_concept_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.CharField(max_length=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='equip_working_hours',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='equip_working_hours'),
        ),
        migrations.AlterField(
            model_name='item',
            name='man_working_hours',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='man_working_hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equip_hrs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='equip_hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fees',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='fees'),
        ),
        migrations.AlterField(
            model_name='project',
            name='man_hrs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='man_hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_bu_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_bu_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_bu_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_bu_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_bu_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_bu_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_concept_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_concept_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_concept_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_concept_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_concept_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_concept_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_ct_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_ct_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_ct_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_ct_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_ct_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_ct_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_nt_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_nt_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_nt_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_nt_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_nt_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_nt_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_ot_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_ot_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_ot_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_ot_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pkg_ot_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pkg_ot_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='power_ratio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='power ratio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_bu_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_bu_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_bu_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_bu_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_bu_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_bu_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_concept_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_concept_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_concept_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_concept_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_concept_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_concept_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_ct_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_ct_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_ct_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_ct_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_ct_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_ct_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_nt_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_nt_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_nt_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_nt_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_nt_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_nt_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_ot_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_ot_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_ot_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_ot_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rel_ot_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rel_ot_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_bu_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_bu_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_bu_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_bu_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_bu_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_bu_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_concept_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_concept_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_concept_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_concept_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_concept_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_concept_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_ct_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_ct_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_ct_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_ct_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_ct_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_ct_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_nt_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_nt_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_nt_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_nt_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_nt_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_nt_hr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_ot_duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_ot_duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_ot_duty_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_ot_duty_rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sv_ot_hr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sv_ot_hr'),
        ),
        migrations.AlterField(
            model_name='record',
            name='bu_regression_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='bu_regression_rate'),
        ),
        migrations.AlterField(
            model_name='record',
            name='concept_regression_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='concept_regression_rate'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ct_regression_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ct_regression_rate'),
        ),
        migrations.AlterField(
            model_name='record',
            name='nt_regression_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='nt_regression_rate'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ot_regression_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ot_regression_rate'),
        ),
    ]
