# Generated by Django 4.2.2 on 2023-08-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_alter_fee_amount_alter_item_equip_working_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rel_bu_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rel_concept_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rel_ct_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rel_nt_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rel_ot_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sv_bu_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sv_concept_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sv_ct_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sv_nt_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sv_ot_hr',
        ),
    ]
