# Generated by Django 4.2.2 on 2023-08-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_remove_project_rel_bu_hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pkg_bu_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pkg_concept_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pkg_ct_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pkg_nt_hr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pkg_ot_hr',
        ),
    ]
