# Generated by Django 4.2.2 on 2023-08-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_remove_project_pkg_bu_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equip_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='equip_hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='fees'),
        ),
        migrations.AlterField(
            model_name='project',
            name='man_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='man_hours'),
        ),
    ]
