# Generated by Django 4.2.2 on 2023-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_alter_project_equip_hrs_alter_project_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='amount'),
        ),
    ]
