# Generated by Django 4.2.2 on 2023-09-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_alter_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='lab_location',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='lab_location'),
        ),
    ]
