# Generated by Django 4.2.2 on 2023-09-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_alter_testitem_chamber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testitem',
            unique_together={('function', 'item', 'lab_location', 'chamber')},
        ),
    ]
