# Generated by Django 4.2.2 on 2023-09-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_alter_testitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='chamber',
            field=models.CharField(blank=True, default='2K', max_length=120, null=True, verbose_name='chamber'),
        ),
    ]
