# Generated by Django 4.2.2 on 2023-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_alter_testitem_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='chamber',
            field=models.CharField(default='2K', max_length=120, verbose_name='chamber'),
        ),
    ]
