# Generated by Django 4.2.2 on 2023-09-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_alter_testitem_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
