# Generated by Django 4.2.2 on 2023-09-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_alter_testitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='db.customer', verbose_name='customer'),
        ),
    ]
