# Generated by Django 4.2.2 on 2023-09-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_alter_function_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.customer', verbose_name='customer'),
        ),
    ]
