# Generated by Django 4.2.2 on 2023-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_alter_function_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='chamber',
            field=models.CharField(default='2K', max_length=120, verbose_name='chamber'),
        ),
        migrations.AlterUniqueTogether(
            name='testitem',
            unique_together={('function', 'item', 'lab_location')},
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='chamber',
        ),
    ]
