# Generated by Django 4.2.2 on 2023-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_fee_chamber_alter_testitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='version'),
        ),
    ]
