# Generated by Django 4.2.2 on 2023-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_alter_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=120, verbose_name='version'),
        ),
    ]
