# Generated by Django 4.2.2 on 2023-09-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_projecthistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projecthistory',
            table='nre_project_history',
        ),
    ]
