# Generated by Django 4.2.2 on 2023-09-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_alter_projecthistory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='action',
            field=models.CharField(default='create', max_length=10),
        ),
    ]
