# Generated by Django 4.2.2 on 2023-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_projecthistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='customer',
            field=models.CharField(default=1, max_length=120, verbose_name='customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='version',
            field=models.CharField(default=1, max_length=120, verbose_name='version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='project',
            field=models.CharField(max_length=120, verbose_name='project'),
        ),
    ]
