# Generated by Django 4.2.2 on 2023-09-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_projecthistory_customer_projecthistory_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='version',
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project', verbose_name='project'),
        ),
    ]
