# Generated by Django 4.2.2 on 2023-10-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_remove_projecthistory_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.CharField(max_length=520, unique=True, verbose_name='no'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=520, verbose_name='name'),
        ),
    ]
