# Generated by Django 4.2.2 on 2023-10-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_alter_item_no_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.CharField(max_length=500, unique=True, verbose_name='no'),
        ),
    ]
