# Generated by Django 4.2.2 on 2023-10-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0058_alter_item_name_alter_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='all_need_test',
            field=models.BooleanField(default=False, verbose_name='all_need_test'),
        ),
    ]
