# Generated by Django 4.2.2 on 2023-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0059_record_all_need_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count',
            field=models.BooleanField(default=False, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='project',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='hide'),
        ),
    ]
