# Generated by Django 4.2.2 on 2023-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_project_count_project_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fee_cost',
            field=models.BooleanField(default=False, verbose_name='fee_cost'),
        ),
    ]
