# Generated by Django 4.2.2 on 2023-10-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_project_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='updated_by',
            new_name='user',
        ),
    ]
