# Generated by Django 4.2.2 on 2023-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_rename_updated_by_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fee_cost',
            field=models.BooleanField(default=True, verbose_name='fee_cost'),
        ),
    ]
